swagger: '2.0'
info:
  title: Khronos API
  description: Manage your cron jobs remotely
  version: 1.0.0
host: 'khronosd.org:4444'
schemes:
  - http
basePath: /api/v1
produces:
  - application/json
paths:
  /ping:
    get:
      summary: App status
      description: Comunicates if the the app is working ok
      responses:
        '200':
          description: App working ok
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /jobs:
    get:
      summary: Registered jobs
      description: >
        The Jobs endpoint returns information about the active registered jobs by
        default
      parameters:
        - name: disabled
          in: query
          description: disabled cronjobs
          required: false
          type: boolean
      tags:
        - jobs
      responses:
        '200':
          description: An array of jobs
          schema:
            type: array
            items:
              $ref: '#/definitions/job'
    post:
      summary: Registers a new job
      description: The endpoint registers a new job
      parameters:
        - name: body
          in: body
          description: json job definiton
          required: true
          schema:
            $ref: '#/definitions/jobForm'
      tags:
        - jobs
      responses:
        '201':
          description: Job created
          schema:
            $ref: '#/definitions/job'
          
definitions:
  jobForm:
    type: object
    properties:
      name:
        type: string
        description: name of the job
      description:
        type: string
        description: Description of the job
      when:
        type: string
        description: 'Cron job [format](https://godoc.org/github.com/robfig/cron)'
      type:
        type: string
        description: type of job, http... (default http)
      url:
        type: string
        description: The job url where the request its being made
        
  job:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier job id
      name:
        type: string
        description: Display name of job.
      description:
        type: string
        description: Description of job.
      when:
        type: string
        description: 'Cron job [format](https://godoc.org/github.com/robfig/cron)'
      active:
        type: boolean
        description: Activated or deactivated state of the job
      url:
        type: string
        description: The job url to make request
  Error:
    type: string
